config/routes.rb
Rails.application.routes.draw do
  resources :imported_texts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  post 'tokenize/:id', to: 'imported_texts#tokenize_text', as: :tokenize
  root to: 'imported_texts#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry_tag.rb
class EntryTag < ApplicationRecord
  belongs_to :j_word
  belongs_to :meta_tag
end

app/models/imported_text.rb
class ImportedText < ApplicationRecord
  has_many :text_entries, dependent: :destroy
  has_one_attached :cover_photo
  serialize :furigana_hash


  # returns an array of the associated proper nouns
  def p_nouns
    PNoun.joins(text_entries: [:imported_text]).where('imported_text_id = ?', id)
  end

  # returns a collection of j_words in the text for under the rank specified

  def j_words
    JWord.joins(text_entries: [:imported_text]).where('imported_text_id = ?', id).uniq
  end

end

app/models/j_word.rb
class JWord < ApplicationRecord
  has_many :j_word_tags, dependent: :destroy
  has_many :meta_tags, through: :j_word_tags
  has_many :text_entries
end

app/models/j_word_tag.rb
class JWordTag < ApplicationRecord
  belongs_to :j_word
  belongs_to :meta_tag
end

app/models/meta_tag.rb
class MetaTag < ApplicationRecord
end

app/models/p_noun.rb
class PNoun < ApplicationRecord
  has_many :text_entries
  has_many :p_noun_tags, dependent: :destroy
  has_many :meta_tags, through: :p_noun_tags
end

app/models/p_noun_tag.rb
class PNounTag < ApplicationRecord
  belongs_to :p_noun
  belongs_to :meta_tag
end

app/models/text_entry.rb
class TextEntry < ApplicationRecord
  belongs_to :imported_text
  belongs_to :j_word, optional: true
  belongs_to :p_noun, optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/imported_texts_controller.rb
class ImportedTextsController < ApplicationController
  before_action :set_imported_text, only: [:show, :edit, :update, :destroy]

  # GET /imported_texts
  # GET /imported_texts.json
  def index
    @imported_texts = ImportedText.all
  end

  # GET /imported_texts/1
  # GET /imported_texts/1.json
  def show
  end

  def tokenize_text
    TokenizeJob.perform_now(params[:id])
    flash.notice = "Tokenize job performed successfully"

  end

  # GET /imported_texts/new
  def new
    @imported_text = ImportedText.new
  end

  # GET /imported_texts/1/edit
  def edit
  end

  # POST /imported_texts
  # POST /imported_texts.json
  def create
    file_html = File.read(params[:imported_text][:html_content].path)

    @imported_text = ImportedText.new(imported_text_params)

    @imported_text.html_content = file_html

    respond_to do |format|
      if @imported_text.save
        format.html { redirect_to @imported_text, notice: 'Imported text was successfully created.' }
        format.json { render :show, status: :created, location: @imported_text }
      else
        format.html { render :new }
        format.json { render json: @imported_text.errors, status: :unprocessable_entity }
      end
    end
   
  end

  def import_html
    file_html = File.read(params[:content].path)
    
  end

  # PATCH/PUT /imported_texts/1
  # PATCH/PUT /imported_texts/1.json
  def update
    respond_to do |format|
      if @imported_text.update(imported_text_params)
        format.html { redirect_to @imported_text, notice: 'Imported text was successfully updated.' }
        format.json { render :show, status: :ok, location: @imported_text }
      else
        format.html { render :edit }
        format.json { render json: @imported_text.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /imported_texts/1
  # DELETE /imported_texts/1.json
  def destroy
    @imported_text.destroy
    respond_to do |format|
      format.html { redirect_to imported_texts_url, notice: 'Imported text was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_imported_text
      @imported_text = ImportedText.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def imported_text_params
      params.require(:imported_text).permit(:title, :content, :cover_photo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/imported_texts_helper.rb
module ImportedTextsHelper
end

app/views/imported_texts/_form.html.erb
<%= form_with(model: imported_text, local: true) do |form| %>
  <% if imported_text.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(imported_text.errors.count, "error") %> prohibited this imported_text from being saved:</h2>

      <ul>
        <% imported_text.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

   <div class="field">
    <%= form.label :html_content %>
    <%= form.file_field :html_content %>
  </div>

   <div class="field">
    <%= form.label :cover_photo %>
    <%= form.file_field :cover_photo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/imported_texts/edit.html.erb
<h1>Editing Imported Text</h1>

<%= render 'form', imported_text: @imported_text %>

<%= link_to 'Show', @imported_text %> |
<%= link_to 'Back', imported_texts_path %>

app/views/imported_texts/index.html.erb
<div class="container">

<p id="notice"><%= notice %></p>

<h1>Imported Texts</h1>
<div class="row">
  <div class="col-sm-6">

</div>
    <% @imported_texts.each do |imported_text| %>

    <%= render partial: 'shared/imported_text_card', locals: { card: imported_text } %>

    <% end %>

  </div>
<br>

<%= link_to 'New Imported Text', new_imported_text_path %>
</div>

app/views/imported_texts/new.html.erb
<h1>New Imported Text</h1>

<%= render 'form', imported_text: @imported_text %>

<%= link_to 'Back', imported_texts_path %>

app/views/imported_texts/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <%= form_with(url: tokenize_path) do %>
    <%= submit_tag("Perform Tokenize Job") %>
  <% end %>
  <p>
    <%= @imported_text.html_content.html_safe %>
  </p>

  <%= link_to 'Edit', edit_imported_text_path(@imported_text) %> |
  <%= link_to 'Back', imported_texts_path %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JapFreq</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_imported_text_card.html.erb
<div class="card" style="width: 18rem;">
  <%= cl_image_tag card.cover_photo.key, height: 200, width: 300, crop: :fill, gravity: :north, class: 'card-img-top' %>
  <div class="card-body">
    <h5 class="card-title"><%= card.title %></h5>
    <h6 class="card-subtitle mb-2 text-muted">Vocab Items: <%= card.j_words.count %> </h6>
    <h6 class="card-subtitle mb-2 text-muted">Proper Nouns: <%= card.p_nouns.count %></h6>
    <%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } , class: 'card-link' %>
    <%= link_to 'Edit', edit_imported_text_path(card), class: 'card-link' %>
    <%= link_to 'Show', card, class: 'card-link' %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Japanese FlashCard Maker</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
         <%= link_to "Home", imported_texts_path, class: 'nav-link float-right' %>
      </li>
      <li class="nav-item">
          <%= link_to "Import Text", new_imported_text_path, class: 'nav-link float-right' %>
      </li>
    </ul>
  </div>
</nav>